### ISSUE TITLE
Bug on firefox

### ISSUE THREAD

**Issue by cukikt0302** [vmaimone/vue-context-menu#5]
Firefox wrong position in this image
![screenshot 3](https://user-images.githubusercontent.com/26678541/27760855-8f9b2a60-5e7b-11e7-90a2-392eab5ee1ed.png)

**Comment by vmaimone** [comment]
I'm sure this is related to the use of `document.body.scrollTop`. 

Will fix ASAP but am a little tight on time right now - contributions are always welcome!

**Comment by vmaimone** [comment]
I believe version 2.0.3 resolves this issue. Please let me know if that is not the case.

**Comment by cukikt0302** [comment]
I think "offset" is correct
When scroll down it's wrong job
SR my EL

**Comment by vmaimone** [comment]
you are absolutely right. I think `document.body` just needed to be replaced with `document.documentElement` for Firefox in the original code.

Please try 2.0.4 and let me know how it is

**Comment by cukikt0302** [comment]
Thank you it worked

**Comment by vmaimone** [comment]
happy to hear it!

**Comment by CinKon** [comment]
Similar Bug is back: 
ctx-menu.js:
```javascript
    setPositionFromEvent (e) {
      e = e || window.event
      ...
```
`e` is always undefined in FF (Developer Edition 56)

**Comment by CinKon** [comment]
Never mind, called the open-function manually and didn't provide an event-variable
